### ISSUE TITLE
Internal Ethernet NIC not working Envy15

### ISSUE THREAD

**Issue by dlavareda** [burrows1980/HP_Envy_15#2]
First of all thank you for your work.
I'm having trouble making the internal NIC working.
Are you still using this config?
To be fair I haven't yet tried to fix, wondering if you have been updating for your use.
Thank you.

**Comment by burrows1980** [comment]
Mic is working fine, Siri and other programs function perfect with internal mic.

**Comment by dlavareda** [comment]
I mean NIC - Network card RJ45

**Comment by dlavareda** [comment]
Never mind i think is ok now. It's working,  I guess the Network Card was not available only in the installer.

Thanks.
Everything is running smooth so far.
